### ISSUE TITLE
tqdm causes slices-to-precomputed to fail

### ISSUE THREAD

**Issue by falkben** [HumanBrainProject/neuroglancer-scripts#10]
I haven't yet figured out exactly why this is happening, but the progress bar in slices-to-precomputed is causing the script to fail prematurely for me.  

When called with a relatively simple input:

`slices-to-precomputed.exe data\ output\ --flat`

Here's the stack trace:

```
Exception ignored in: <bound method tqdm.__del__ of writing chunks: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 90/90 [00:18<00:00,  3.59chunks/s]>
Traceback (most recent call last):
  File "/mnt/c/Users/ben/Documents/AB_MouseRegistrationTests_MSGSW171registrationtest_0_2160_0_2560_0_16_Ch0_1/env/lib/python3.5/site-packages/tqdm/_tqdm.py", line 889, in __del__
    self.close()
  File "/mnt/c/Users/ben/Documents/AB_MouseRegistrationTests_MSGSW171registrationtest_0_2160_0_2560_0_16_Ch0_1/env/lib/python3.5/site-packages/tqdm/_tqdm.py", line 1095, in close
    self._decr_instances(self)
  File "/mnt/c/Users/ben/Documents/AB_MouseRegistrationTests_MSGSW171registrationtest_0_2160_0_2560_0_16_Ch0_1/env/lib/python3.5/site-packages/tqdm/_tqdm.py", line 454, in _decr_instances
    cls.monitor.exit()
  File "/mnt/c/Users/ben/Documents/AB_MouseRegistrationTests_MSGSW171registrationtest_0_2160_0_2560_0_16_Ch0_1/env/lib/python3.5/site-packages/tqdm/_monitor.py", line 52, in exit
    self.join()
  File "/usr/lib/python3.5/threading.py", line 1051, in join
    raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread
```

When this fails in such a way, it's nearly complete, but doesn't get to creating the individual .gz files for that base resolution (it has all the folders for each "block" of data.

If I comment out the lines for the progress bar in the loop for `slices_to_raw_chunks` the script completes without error.

**Comment by falkben** [comment]
Setting tqdm to version 4.20.0 fixes the issue for me.  There's more information here: https://github.com/tqdm/tqdm/issues/549  Perhaps worth pinning to this version if you can replicate?

**Comment by ylep** [comment]
Hopefully recent tqdm versions have sorted out this issue... However the above tqdm issue is still opened, so I will leave the `optional_tqdm` branch around as a workaround.
